Add Integration tests
hazelcast/hazelcast-azure pull request #51
Opened 2020-08-27 10:44 UTC by mtyazici

Added Integrations-tests for the repo. On push a workflow will be triggered. A workflow can be triggered on Actions page also. It will do the following:
- Clone the hazelcast main repo, build a jar
- Build a jar of hazelcast-azure
- Apply Terraform configuration to deploy two Hazelcast cluster members and Hazelcast Management Center on Azure.
- Verify that cluster is formed and members are able to communicate with Management Center.

If all these steps are done correctly the build will pass.

- [x] Required credentials should be added into repo as a secrets.

This worfklow will not run when a PR is created. This is because github doesn't have any way of providing secrets to a forked repository. So a workflow accessing the secrets will always fail.

A related [thread](https://github.community/t/make-secrets-available-to-builds-of-forks/16166/35) about this problem.

2020-08-31 10:16 UTC, mtyazici commented
I applied suggestions from the code review in [AWS PR](https://github.com/hazelcast/hazelcast-aws/pull/196).

2020-09-09 07:28 UTC, enozcan requested changes
Leaving a few comments from GCP reviews.

2020-09-09 07:28 UTC, enozcan commented on .github/terraform/scripts/start_azure_hazelcast_management_center.sh
> +
```suggestion
```

2020-09-09 07:28 UTC, enozcan commented on .github/terraform/scripts/start_azure_hazelcast_member.sh
> +nohup java -cp ${CLASSPATH} -server com.hazelcast.core.server.HazelcastMemberStarter >> ${HOME}/logs/hazelcast.stderr.log 2>> ${HOME}/logs/hazelcast.stdout.log &
Applies the review from gcp:
```suggestion
nohup java -cp ${CLASSPATH} -server com.hazelcast.core.server.HazelcastMemberStarter &>> ${HOME}/logs/hazelcast.logs &
```

2020-09-09 07:28 UTC, enozcan commented on .github/terraform/main.tf
> +      "tail -n 20 ./logs/hazelcast.stdout.log",
Regarding the change in start_member.sh:
```suggestion
      "tail -n 20 ./logs/hazelcast.logs",
```

2020-09-09 09:20 UTC, enozcan approved these changes

2020-09-09 09:42 UTC, hasancelik approved these changes

2020-09-09 09:44 UTC, merged